# Which github team is the maintainer of the repository. Maintainers have special permissions and are responsible for
# the code in the repository in all meaningful ways. They may use CODEOWNERS to delegate ownership of sub-folders
maintainer: roblox/ml-runtime
